version: "3.7"

services:
  mysql:
    image: mysql:8.0.19
    networks:
      - vps-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: inoyam1234@@
    # volumes:
    #   - ./mysql:/docker-entrypoint-initdb.d
    command: mysqld --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    networks:
      - vps-network
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

networks:
  vps-network: